adjectives=[
    'poetic',
    'noble',
    'beautiful',
    'talented',
    'perfect',
    'cunning',
    'pliable',
    'chestnut-haired',
    'tricky',
    'rule-breaking',
    'thoughtful',
    'talented',
    'brilliant',
    'glowing',
    'coy',
    'devious',
    'genius',
    'pretty',
    'awesome',
    'sweet',
    'innocent',
    'amazing',
    'powerful',
    'exceptional',
    'smart',
    'capable',
    'smooth',
    'smart-as-a-whip',
    'cool under pressure',
    'naive',
    'sophisticated',
    'rainbow-infused',
    'sassy',
    'cunning',
    'opalescent',
    'iridescent',
    'misunderstood',
    'priceless',
    'expensive',
    'wild',
    'crazy',
    'phenomenal',
    'clever',
    'magnificent',
    'majestic',
    'unstoppable',
    'glamorous',
    'adorable',
    'spectacular',
    'golden-tongued',
    'gorgeous',
    'sly',
    'sneaky',
    'elusive',
    'humble',
    'intelligent',
    'magnificent',
    'fluorescent',
    'handsome',
    'flawless',
    'elegant',
    'vivacious',
    'delicious',
    'transcendent',
    'impish',
    'world famous'
]

nouns=[
    'land mermaid',
    'spinster',
    'sunflower',
    'sunfish',
    'minx',
    'moth',
    'unicorn-nurse',
    'musk-ox',
    'tropical fish',
    'sun goddess',
    'Pawnee Goddess',
    'bastard',
    'woman',
    'newborn baby',
    'space unicorn',
    'mannequin come to life',
    'tree-shark',
    'sexy elf king',
    'sports car',
    'gem',
    'flower pot',
    'well of ideas',
    'flying squirrel',
    'unicorn',
    'child',
    'freight train',
    'ice sculptor',
    'industrial park',
    'house cat',
    'miniature horse',
    'runaway hot air balloon',
    'golden retriever',
    'apple pie',
    'purebred poodle',
    'rainbow of joy',
    'middle school marching band',
    'stack of waffles',
    'little seahorse',
    'liger',
    'lightbulb of truth'
]